package com.demo.restservice;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Body implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String userName;
	private java.lang.String password;

	public Body() {
	}

	public java.lang.String getUserName() {
		return this.userName;
	}

	public void setUserName(java.lang.String userName) {
		this.userName = userName;
	}

	public java.lang.String getPassword() {
		return this.password;
	}

	public void setPassword(java.lang.String password) {
		this.password = password;
	}

	public Body(java.lang.String userName, java.lang.String password) {
		this.userName = userName;
		this.password = password;
	}

}