package com.demo.restservice;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CreateUser implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public CreateUser() {
    }




}